# use miniconda for python, so don't specify "python", which doesn't
# work on travis osx anyway
language: generic
os:
  - linux

env:
  global:
    # Registry supports only a subset of the matrix
    - TEST_REGISTRY=false
    # Registry configs
    - FLASK_APP=quilt_server
    - FLASK_DEBUG=1
    - QUILT_SERVER_CONFIG=dev_config.py
    - QUILT_SECRET_KEY=testing
    # Catalog
    - TEST_CATALOG=false

addons:
  postgresql: "9.6"

matrix:
  fast_finish: true
  include:
    - os: linux
      language: python
      python: "3.6"
      env:
        TEST_COMPILER=false
        TEST_REGISTRY=true
        TORCH="http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-linux_x86_64.whl"
      services:
        - postgresql

install:
  - |
    if [[ "$TEST_REGISTRY" = true ]]; then
      travis_retry pip install -r registry/requirements.txt
      pip install registry
    fi

script:
  - |
    if [[ "$TEST_REGISTRY" = true ]]; then
      pytest --cov=./ ./registry
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
